<?php $selectedCurrency = (string) old('currency', 'USD'); ?>
<section class="grid gap-6 xl:grid-cols-[1.2fr_1fr]">
    <div class="card p-5">
        <h2 class="text-lg font-black text-ink-900">Schedules</h2>
        <p class="mt-1 text-sm text-ink-500">Recurring invoices are generated by the secure cron URL configured after installation.</p>
        <div class="mt-5 table-wrap">
            <table class="data-table">
                <thead><tr><th>Client</th><th>Frequency</th><th>Next run</th><th class="text-right">Total</th></tr></thead>
                <tbody class="divide-y divide-ink-100">
                    <?php foreach ($recurring as $row): ?>
                        <tr>
                            <td class="font-bold"><?= e($row['client_name']) ?></td>
                            <td><?= e($row['frequency']) ?></td>
                            <td><?= e($row['next_run_date']) ?></td>
                            <td class="text-right font-bold"><?= money($row['total'], $row['currency']) ?></td>
                        </tr>
                    <?php endforeach; ?>
                    <?php if (!$recurring): ?>
                        <tr><td colspan="4">
                            <?php empty_state([
                                'icon' => 'invoices',
                                'title' => 'No recurring schedules yet',
                                'description' => 'Set up a schedule to auto-generate invoices on a weekly, monthly, quarterly, or yearly cadence.',
                                'primaryActionLabel' => 'Create a schedule',
                                'primaryActionHref' => '#schedule-form',
                            ]) ?>
                        </td></tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>
    </div>

    <form method="post" action="/recurring" id="schedule-form" class="card p-5">
        <?= csrf_field() ?>
        <h2 class="text-lg font-black text-ink-900">Create schedule</h2>
        <div class="mt-5 grid gap-4 sm:grid-cols-2">
            <label class="sm:col-span-2"><span class="label">Client</span><select class="field" name="client_id" required><option value="">Select client</option><?php foreach ($clients as $client): ?><option value="<?= e($client['id']) ?>"><?= e($client['name']) ?></option><?php endforeach; ?></select></label>
            <label><span class="label">Frequency</span><select class="field" name="frequency"><option value="weekly">Weekly</option><option value="monthly" selected>Monthly</option><option value="quarterly">Quarterly</option><option value="yearly">Yearly</option></select></label>
            <label><span class="label">Currency</span><select class="field" name="currency" required><?php foreach ($currencies as $currency): ?><option value="<?= e(secure_option('currency', $currency['code'])) ?>" <?= secure_option_selected('currency', $selectedCurrency, $currency['code']) ?>><?= e($currency['code']) ?> - <?= e($currency['name'] ?? $currency['code']) ?></option><?php endforeach; ?></select></label>
            <label><span class="label">Next run</span><input class="field" name="next_run_date" type="date" value="<?= e(date('Y-m-d', strtotime('+1 month'))) ?>" required></label>
            <label><span class="label">End date</span><input class="field" name="end_date" type="date"></label>
        </div>

        <div class="mt-5">
            <div class="mb-3 flex items-center justify-between">
                <h3 class="font-black text-ink-900">Line items</h3>
                <button type="button" class="btn-secondary" data-add-line="#recurring-lines" data-template="#recurring-line-template"><?= icon('plus') ?> Add</button>
            </div>
            <div id="recurring-lines" class="space-y-3">
                <?php \App\Core\View::partial('partials/line-item-row', ['taxes' => $taxes]); ?>
            </div>
        </div>

        <label class="mt-5 block"><span class="label">Notes</span><textarea class="textarea" name="notes" rows="3"></textarea></label>
        <label class="mt-4 block"><span class="label">Terms</span><textarea class="textarea" name="terms" rows="3"></textarea></label>
        <button class="btn-primary mt-5 w-full"><?= icon('check') ?> Save schedule</button>
    </form>
</section>

<template id="recurring-line-template">
    <?php \App\Core\View::partial('partials/line-item-row', ['taxes' => $taxes]); ?>
</template>
